# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('postTitle', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('userName', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShortCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('SDate', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.PositiveIntegerField()),
                ('venue', models.CharField(max_length=1000)),
                ('instructor', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('link', models.URLField(max_length=500)),
                ('status', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('SDate', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.PositiveIntegerField()),
                ('venue', models.TextField(max_length=1000)),
                ('instructor', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
