# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='SDate',
            field=models.CharField(max_length=50),
        ),
    ]
